import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import os

def send_daily_appointments_email(
    clinic_email: str,
    doctor_name: str,
    appointments: list
):
    if not appointments:
        return  # do not send empty emails

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"Today's Appointments – Dr. {doctor_name}"
    msg["From"] = os.getenv("EMAIL_FROM")
    msg["To"] = clinic_email

    rows = ""
    for a in appointments:
        rows += f"""
        <tr>
            <td>{a.appointment_time.strftime("%H:%M")}</td>
            <td>{a.patient.name}</td>
            <td>{a.patient.phone}</td>
        </tr>
        """

    html = f"""
    <html>
      <body>
        <h2>Today's Appointments – Dr. {doctor_name}</h2>
        <table border="1" cellpadding="8">
          <tr>
            <th>Time</th>
            <th>Patient</th>
            <th>Phone</th>
          </tr>
          {rows}
        </table>
        <p>Generated by MedSchedule AI</p>
      </body>
    </html>
    """

    msg.attach(MIMEText(html, "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(
            os.getenv("EMAIL_USERNAME"),
            os.getenv("EMAIL_PASSWORD")
        )
        server.send_message(msg)
