"""add_treatment_key_and_duration_to_appointments

Revision ID: 3c933492b6bb
Revises: 616461dcffe6
Create Date: 2026-04-09 14:56:27.954167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c933492b6bb'
down_revision: Union[str, Sequence[str], None] = '616461dcffe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('treatment_key', sa.String(length=64), nullable=True))
    op.add_column('appointments', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'duration_minutes')
    op.drop_column('appointments', 'treatment_key')
    # ### end Alembic commands ###
